added scale
N1kla3/trains pull request #1
Opened 2019-11-12 12:51 UTC by N1kla3

2019-11-12 21:34 UTC, teiuaz requested changes

2019-11-12 21:34 UTC, ivvory commented on Station.h
> +    int getMaxProfuct(){return maxProduct;}
может все-таки Product
```suggestion
    int getMaxProduct(){return maxProduct;}
```

2019-11-12 21:34 UTC, ivvory commented on Map.h
> +    Train * infoTrain;
почему сырые указатели используешь, не боишься утечек?

2019-11-12 21:34 UTC, ivvory commented on Map.h
>      std::vector<railWay*> railSprites;
почему в названии этой переменной есть слово sprite, а в предыдущих - нет?

```suggestion
    std::vector<railWay*> railways;
```

2019-11-12 21:34 UTC, ivvory commented on Map.cpp
>      if (sf::Mouse::isButtonPressed(sf::Mouse::Left))
смотрю я значит на этот код и меня терзают сомнения по поводу, что функция называется getInfo, а в ней делается scale спрайтов, это вообще как по логике??

2019-11-12 21:34 UTC, ivvory commented on Map.cpp
>              if((sf::Mouse::getPosition().x > station->getX()) && (sf::Mouse::getPosition().x < station->getX() + 200)
нужно тратить время, чтобы разбираться, что за проверка в ифе, если вынести в переменную, то будет проще читаться

2019-11-12 21:34 UTC, ivvory commented on Map.cpp
>              }
```cpp
int x = sf::Mouse::getPosition().x;
int y = sf::Mouse::getPosition().y;
bool stationClicked = ((x > station->getX()) && (x < station->getX() + 200) && (y > station->getY()) && (y < station->getY() + 200))
if (stationClicked)
{
    # ...
}
```

2019-11-12 21:34 UTC, ivvory commented on Map.cpp
>              }
А еще можно сделать метод в станции, getX() и getY() вообще удалить чтобы не было желания вот так вот использовать, а писать нормальные методы
```cpp
int x = sf::Mouse::getPosition().x;
int y = sf::Mouse::getPosition().y;
if (station->Clicked(x, y))
{
    # ...
}
```

2019-11-12 21:34 UTC, ivvory commented on Map.cpp
>          if(station->getType() == 1) {
сделать enum для типов станций и switch вместо ифа? https://en.cppreference.com/w/cpp/language/enum
```suggestion
        switch(station->getType())
        {
             case StationType::LOVE :
```

2019-11-12 21:38 UTC, teiuaz requested changes
фикси

2019-11-14 06:36 UTC, N1kla3 commented on Station.h
> +    int getMaxProfuct(){return maxProduct;}
я думаю все таки да

2019-11-14 06:36 UTC, N1kla3 commented on Map.h
> +    Train * infoTrain;
каким образом

2019-11-14 06:37 UTC, N1kla3 commented on Map.h
>      std::vector<railWay*> railSprites;
потому что класс только для отрисовки

2019-11-14 06:39 UTC, N1kla3 commented on Map.cpp
>      if (sf::Mouse::isButtonPressed(sf::Mouse::Left))
А что не так?Выделение объекта о котором надо получить информацию тоже часть информации

2019-11-14 06:40 UTC, N1kla3 commented on Map.cpp
>              if((sf::Mouse::getPosition().x > station->getX()) && (sf::Mouse::getPosition().x < station->getX() + 200)
Вполне логично

2019-11-14 06:41 UTC, N1kla3 commented on Map.cpp
>              }
Они нужны

2019-11-14 06:42 UTC, N1kla3 commented on Map.cpp
>          if(station->getType() == 1) {
_Именно так_

2019-11-14 22:01 UTC, ivvory commented on Map.h
>      std::vector<railWay*> railSprites;
а классы Train и Station не только для отрисовки?

2019-11-14 22:02 UTC, ivvory commented on Map.h
> +    Train * infoTrain;
где ты создаешь объект и где он уничтожается?

2019-11-14 22:04 UTC, ivvory commented on Map.cpp
>              }
ну сейчас понятно нужны но вообще по красоте это же внутренности объекта, слишком личное, я думаю ему не приятно, когда ты используешь эти методы... изверг

2019-11-22 07:58 UTC, merged